name    'jbussdieker-carbon'
version '0.0.1'
source 'http://github.com/jbussdieker/puppet-carbon'
author 'Joshua Bussdieker'
license 'MIT'
summary 'Puppet Carbon management module'
description 'This module can be used for basic Carbon Management'
project_page 'http://github.com/jbussdieker/puppet-carbon'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/vcsrepo', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 1.1.0'
